import { gameboytest } from "../assets";

export const inventory = [
  {
    image: gameboytest,
    sku: "GB-001",
    name: "Gameboy",
    category: "Electronics",
    cost: "$50.00",
    weight: "0.5 lbs",
    warehouse: "Warehouse A",
    length: 5,
    width: 3,
    height: 1,
    quantity: 100,
  },
  {
    image: gameboytest,
    sku: "GB-002",
    name: "Gameboy Color",
    category: "Electronics",
    cost: "$60.00",
    weight: "0.6 lbs",
    warehouse: "Warehouse B",
    length: 5,
    width: 3,
    height: 1,
    quantity: 150,
  },
  {
    image: gameboytest,
    sku: "GB-003",
    name: "Gameboy Advance",
    category: "Electronics",
    cost: "$70.00",
    weight: "0.7 lbs",
    warehouse: "Warehouse C",
    length: 6,
    width: 3.5,
    height: 1.2,
    quantity: 200,
  },
  {
    image: gameboytest,
    sku: "GB-004",
    name: "Gameboy SP",
    category: "Electronics",
    cost: "$80.00",
    weight: "0.8 lbs",
    warehouse: "Warehouse A",
    length: 6,
    width: 3.5,
    height: 1.2,
    quantity: 250,
  },
  {
    image: gameboytest,
    sku: "GB-005",
    name: "Gameboy Micro",
    category: "Electronics",
    cost: "$90.00",
    weight: "0.4 lbs",
    warehouse: "Warehouse B",
    length: 4,
    width: 2,
    height: 0.8,
    quantity: 300,
  },
];
